#INCLUDE "p16f887.inc"
    __CONFIG _CONFIG1, 0xFFF7;WHATCHDOG APAGADO: _WDT_OFF
    ORG 0
    GOTO INICIO
    ORG 04
    MOVF PORTB, W
    ;BCF INTCON, INTF
    BCF INTCON, RBIF
INICIO
    BSF STATUS, RP0
    BSF IOCB, 3;0
    BSF STATUS, RP1
    BCF ANSELH, ANS9;ANS12
    BCF STATUS, RP0
    BCF STATUS, RP1
    BSF INTCON, RBIE
    BSF INTCON, GIE
CICLO
    NOP
    GOTO CICLO
    END