#INCLUDE "p16f887.inc"    
    __CONFIG _CONFIG1, _WDT_OFF
    UDATA 020
;SWAP W, WRES
SRES	RES 1;STATUS RESPALDO
WRES	RES 1;WREG RESPALDO
    ORG 0
    GOTO INICIO
    ORG 4
    MOVWF WRES;COPIAMOS REGISTRO DE TRABAJO    
    MOVF STATUS, W;REGISTRO DE ESTADO A REGISTRO DE TRABAJO    
    MOVWF SRES;COPIAMOS REGISTRO DE ESTADO    
    NOP
    MOVLW .7
    MOVWF TMR0
    BCF INTCON, T0IF
    MOVF SRES, W;
    MOVWF STATUS;
    MOVF WRES, W;
    RETFIE
INICIO    
    BSF STATUS, RP0
    MOVLW 002
    MOVWF OPTION_REG
    BCF STATUS, RP0    
    BSF INTCON, T0IE
    BSF INTCON, GIE
CICLO
    NOP
    NOP
    NOP
    NOP
    NOP
    GOTO CICLO
    END    


